# fly.toml file generated for artefacts-bot on 2023-04-14T10:53:33+04:00

app = "artefacts-bot"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "ams"

[env]
  MODEL_API_URL = "https://art-expert-chat-art-platform.fly.dev"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
