name: ci

on: push


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: ./fastapi-deployment
          tags: fastapi-deployment:latest
          outputs: type=docker,dest=/tmp/fastapi-deployment.tar
      -
        name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: fastapi-deployment
          path: /tmp/fastapi-deployment.tar

  use:

    runs-on: ubuntu-latest

    needs: build

    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: fastapi-deployment
          path: /tmp
      -
        name: Load image
        run: |
          docker load --input /tmp/fastapi-deployment.tar
          docker image ls -a
