name: ci

on: push


jobs:
  build:
    strategy:
      matrix:
        module: ["fastapi-deployment"]

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and export
        uses: docker/build-push-action@v4
        with:
          working-directory: ./${{ matrix.module }}
          context: .
          tags: ${{ matrix.module }}:latest
          outputs: type=docker,dest=/tmp/${{ matrix.module }}.tar
      -
        name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.module }}
          path: /tmp/${{ matrix.module }}.tar

  use:
    strategy:
      matrix:
        module: ["fastapi-deployment"]

    runs-on: ubuntu-latest

    needs: build

    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.module }}
          path: /tmp
      -
        name: Load image
        run: |
          docker load --input /tmp/${{ matrix.module }}.tar
          docker image ls -a
